java -jar yuicompressor-2.4.6.jar attendance\attendance.js -o attendance\attendance.min.js
java -jar yuicompressor-2.4.6.jar attendance\dailyabsentee.js -o attendance\dailyabsentee.min.js
java -jar yuicompressor-2.4.6.jar attendance\dailyattendance.js -o attendance\dailyattendance.min.js
java -jar yuicompressor-2.4.6.jar attendance\disciplinary.js -o attendance\disciplinary.min.js
java -jar yuicompressor-2.4.6.jar attendance\employeeproject.js -o attendance\employeeproject.min.js
java -jar yuicompressor-2.4.6.jar attendance\employeeshift.js -o attendance\employeeshift.min.js
java -jar yuicompressor-2.4.6.jar attendance\holiday.js -o attendance\holiday.min.js
java -jar yuicompressor-2.4.6.jar attendance\overtime.js -o attendance\overtime.min.js
java -jar yuicompressor-2.4.6.jar attendance\rategroup.js -o attendance\rategroup.min.js
java -jar yuicompressor-2.4.6.jar attendance\shiftdetail.js -o attendance\shiftdetail.min.js
java -jar yuicompressor-2.4.6.jar attendance\shiftgroup.js -o attendance\shiftgroup.min.js
java -jar yuicompressor-2.4.6.jar attendance\shiftupdate.js -o attendance\shiftupdate.min.js
java -jar yuicompressor-2.4.6.jar attendance\staffperiodicattendance.js -o attendance\staffperiodicattendance.min.js
java -jar yuicompressor-2.4.6.jar attendance\timecard.js -o attendance\timecard.min.js
java -jar yuicompressor-2.4.6.jar attendance\timecardlimit.js -o attendance\timecardlimit.min.js
java -jar yuicompressor-2.4.6.jar attendance\timeoff.js -o attendance\timeoff.min.js
java -jar yuicompressor-2.4.6.jar attendance\project.js -o attendance\project.min.js
java -jar yuicompressor-2.4.6.jar hr\employee.js -o hr\employee.min.js